include: package:lint/analysis_options.yaml
analyzer:
  errors:
    argument_type_not_assignable: ignore
  exclude:
linter:
  rules:
    prefer_const_constructors: false
    sort_pub_dependencies: false
    sort_constructors_first: false
    prefer_double_quotes: false
    prefer_single_quotes: true
    prefer_const_literals_to_create_immutables: false
    avoid_classes_with_only_static_members: false
    directives_ordering: false
    no_leading_underscores_for_local_identifiers: false
    use_colored_box: false
    avoid_print: false
    avoid_dynamic_calls: ignore