name: crm
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  bloc: ^8.1.0
  bloc_concurrency: ^0.2.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_dotenv: ^5.0.2
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.16
  flutter_screenutil: ^5.6.0
  get_it: ^7.2.0
  google_nav_bar: ^5.0.6
  intl: ^0.17.0
  loader_overlay: ^2.1.0
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  supabase_flutter: ^1.2.2

dev_dependencies:
  bloc_test: ^9.1.0
  flutter_test:
    sdk: flutter
  lint: ^2.0.1
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter_native_splash:
  image: assets/logo.png
  color: "#3a4d31"
  android: true
  ios: true
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  generate: true

  assets:
      - .env
      - assets/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400